# Generated by Django 4.1.5 on 2023-02-12 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_dayname_alter_plan_created_alter_recipe_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='votes',
        ),
        migrations.AlterField(
            model_name='plan',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 2, 12, 11, 48, 35, 718491)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 2, 12, 11, 48, 35, 718181)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 2, 12, 11, 48, 35, 718193)),
        ),
    ]
